apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-monitor.fullname" . }}
  labels:
    {{- include "argocd-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if .Values.oauth2Proxy.enabled }}oauth2-proxy{{ else }}http{{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "argocd-monitor.selectorLabels" . | nindent 4 }}
